server:
  port: 8082
spring:
  data:
    rest:
      base-path: /api/v1
    mongodb:
      uri: ${vcap.services.${PREFIX:}mongodb.credentials.uri:mongodb://${MONGODB_HOST:localhost}:${MONGODB_PORT:27017}/stores}